spring.profiles.active=dev

# Service
spring.application.name=recipe-ai-service

# Postgres DB
spring.datasource.url=jdbc:postgresql://localhost:5432/recipedb
spring.datasource.username=recipe
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiry-hours=24

# Claude AI
ai.claude.api-key=${CLAUDE_AI_API_KEY}
ai.claude.api-url=https://api.anthropic.com/v1/messages
ai.claude.model=claude-sonnet-4-20250514
ai.claude.max-tokens=3000
ai.claude.temperature=0.5
ai.claude.connect-timeout-seconds=5
ai.claude.read-timeout-seconds=60

# Gemini AI
ai.gemini.api-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
ai.gemini.api-key=${GEMINI_AI_API_KEY}
ai.gemini.model=gemini-1.5-flash
ai.gemini.max-tokens=100000
ai.gemini.temperature=0.5
ai.gemini.connect-timeout-seconds=5
ai.gemini.read-timeout-seconds=60

# Active provider
ai.provider=gemini

# Resilience4j
resilience4j.circuitbreaker.instances.ai.sliding-window-size=10
resilience4j.circuitbreaker.instances.ai.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ai.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.ai.permitted-number-of-calls-in-half-open-state=3

resilience4j.retry.instances.ai.max-attempts=3
resilience4j.retry.instances.ai.wait-duration=1s
resilience4j.retry.instances.ai.enable-exponential-backoff=true

# Rate Limiter
app.rate-limit.requests-per-minute=10

# Scheduling
spring.task.scheduling.pool.size=2

# Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always

# Logging
logging.level.com.shruti.recipeai=DEBUG
logging.level.org.springframework.security=INFO

# Ignore unknown fields in requests - prevents errors if client sends extra fields
spring.jackson.deserialization.fail-on-unknown-properties=false
# Return null fields or skip them
spring.jackson.default-property-inclusion=non_null